_target_: instant_avatar.datasets.peoplesnapshot.PeopleSnapshotDataModule
name: peoplesnapshot
subject: male-2-casual
gender: male
opt:
  dataroot: ./data/PeopleSnapshot/${dataset.subject}/
  subject: ${dataset.subject}
  train:
    num_workers: 8
    batch_size: 4
    start: 1
    end: 455
    skip: 4
    downscale: 2
    sampler: ${sampler}
    fitting: ${model.opt.optimize_SMPL.enable}
  val:
    num_workers: 0
    batch_size: 1
    start: 455
    end: 455
    skip: 8
    downscale: 2
  test:
    num_workers: 4
    batch_size: 1
    start: 1
    end: 455
    skip: 20
    downscale: 2
