_target_: instant_avatar.datasets.peoplesnapshot.PeopleSnapshotDataModule
name: peoplesnapshot
subject: male-3-sport
gender: male
opt:
  dataroot: ./data/PeopleSnapshot/${dataset.subject}/
  subject: ${dataset.subject}
  train:
    num_workers: 20
    batch_size: 1
    start: 1
    end: 230
    skip: 2
    downscale: 2
    sampler: ${sampler}
    fitting: ${model.opt.optimize_SMPL.enable}
  val:
    num_workers: 0
    batch_size: 1
    start: 230
    end: 230
    skip: 6
    downscale: 2
  test:
    num_workers: 0
    batch_size: 1
    start: 230
    end: 460
    skip: 6
    downscale: 2
